version: '3.8'

services:
  token-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDPLATFORM=${BUILDPLATFORM:-linux/arm64}
        - TARGETPLATFORM=${TARGETPLATFORM:-linux/arm64} 
        - TARGET=${TARGET:-aarch64-unknown-linux-musl}
      platform: ${TARGETPLATFORM:-linux/arm64}
    image: coze-token-service:local # Tag the image for local use
    container_name: coze-token-service-dev
    ports:
      - "9000:9000" # Map container port 9000 to host port 9000
    env_file:
      - ./coze_token_service/.env # Load environment variables from the .env file
    restart: unless-stopped
