name: Release Version Tag Build

on:
  push:
    tags:
      - 'release-v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/release-v}
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Login to ACR
        uses: aliyun/acr-login@v1
        with:
          region-id: "cn-shenzhen"
          access-key-id: \${{ secrets.ALIYUN_ACCESS_KEY_ID }}
          access-key-secret: \${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}

      - name: Build and Push
        env:
          REGISTRY: crpi-yua3iq90uqcii5dz.cn-shenzhen.personal.cr.aliyuncs.com/laofei_cons
          IMAGE_NAME: coze_token_service
        run: |
          docker build -t \${{ env.REGISTRY }}/\${{ env.IMAGE_NAME }}:\${{ steps.version.outputs.version }} -f ./coze_token_service/Dockerfile .
          echo \${{ secrets.ACR_PASSWORD }} | docker login \${{ env.REGISTRY }} --username deefox --password-stdin
          docker push \${{ env.REGISTRY }}/\${{ env.IMAGE_NAME }}:\${{ steps.version.outputs.version }}
